name: Snyk Scan and Email Notification

on:
push:
branches: [ main ] # Adjust branch as needed

jobs:
security-and-email:
runs-on: ubuntu-latest
steps:
# Checkout the repository
- name: Checkout code
uses: actions/checkout@v4

# Set up Python environment
- name: Set up Python
uses: actions/setup-python@v5
with:
python-version: '3.11'

# Install dependencies
- name: Install dependencies
run: |
python -m pip install --upgrade pip
pip install -r requirements.txt # Ensure requirements.txt exists

# Run Snyk to check for vulnerabilities
- name: Run Snyk
uses: snyk/actions/python-3.11@master
env:
SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
with:
command: test # Use 'monitor' for continuous monitoring
args: --severity-threshold=high # Optional: filter for high-severity issues

# Run Python script for custom logic and email notification
- name: Run Python script
env:
SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
TO_EMAIL: ${{ secrets.TO_EMAIL }}
run: python script.py
